language: cpp

dist: trusty
sudo: required

git:
  submodules: false

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['cmake', 'g++-5']

env:
  - EXAMPLE_PATH=conan/0.9.1 COMPILER=g++-5
  - EXAMPLE_PATH=conan/conan_build COMPILER=g++-5
  - EXAMPLE_PATH=subproject/internal COMPILER=g++-5
  - EXAMPLE_PATH=subproject/external_boost COMPILER=g++-5 
  - EXAMPLE_PATH=subproject/external COMPILER=g++-5 
# SYSTEM_BOOST_PACKAGE=YES

before_install:
#  - if [[ "${SYSTEM_BOOST_PACKAGE}" != "" ]]; then sudo add-apt-repository -y ppa:samuel-bachmann/boost && sudo apt-get update -qq; fi
  - sudo add-apt-repository -y ppa:samuel-bachmann/boost && sudo apt-get update -qq

install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  - conan remote add martin https://api.bintray.com/conan/martinmoene/nonstd-lite
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add manu https://api.bintray.com/conan/manu343726/conan-packages
#  - if [[ "${SYSTEM_BOOST_PACKAGE}" != "" ]]; then sudo apt-get install libboost1.60-all-dev; fi
  - sudo apt-get install libboost1.60-all-dev

script:
  - export CXX=${COMPILER}
  - git submodule update --init
  - cd ${EXAMPLE_PATH}
  - ./build.sh
  - ./test.sh
