language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        EXAMPLE_PATH=conan/0.9.1
        COMPILER=g++-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-5']
#    - os: linux
#      compiler: gcc
#      env:
#       EXAMPLE_PATH=internal
#        COMPILER=g++-5
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['cmake', 'g++-5']

install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  - conan remote add martin https://api.bintray.com/conan/martinmoene/nonstd-lite
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add manu https://api.bintray.com/conan/manu343726/conan-packages

script:
  - export CXX=${COMPILER}
  - cd ${EXAMPLE_PATH}
  - ./build.sh
  - ./test.sh
