language: cpp

dist: trusty
sudo: required

git:
  submodules: false

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['cmake', 'g++-5']

env:
  - EXAMPLE_PATH=conan/0.9.1 COMPILER=g++-5
  - EXAMPLE_PATH=subproject/internal COMPILER=g++-5

install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  - conan remote add martin https://api.bintray.com/conan/martinmoene/nonstd-lite
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add manu https://api.bintray.com/conan/manu343726/conan-packages

script:
  - export CXX=${COMPILER}
  - git submodule update --init
  - cd ${EXAMPLE_PATH}
  - ./build.sh
  - ./test.sh
