language: cpp

dist: bionic
sudo: required

git:
  submodules: false

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['cmake', 'g++-6']

env:
  - EXAMPLE_PATH=conan/0.9.1 COMPILER_VERSION=6
  - EXAMPLE_PATH=conan/1.0.0 COMPILER_VERSION=6
  - EXAMPLE_PATH=conan/1.1.0 COMPILER_VERSION=6
  - EXAMPLE_PATH=conan/conan_build COMPILER_VERSION=6
  - EXAMPLE_PATH=external/internal COMPILER_VERSION=6
  - EXAMPLE_PATH=external/external_boost COMPILER_VERSION=6 USE_BOOST_PACKAGE=1
  - EXAMPLE_PATH=external/external COMPILER_VERSION=6 USE_BOOST_PACKAGE=1
  - EXAMPLE_PATH=subproject/internal COMPILER_VERSION=6
  - EXAMPLE_PATH=subproject/external_boost COMPILER_VERSION=6 USE_BOOST_PACKAGE=1
  - EXAMPLE_PATH=subproject/external COMPILER_VERSION=6 USE_BOOST_PACKAGE=1


install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  - conan remote add martin https://api.bintray.com/conan/martinmoene/nonstd-lite
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add manu https://api.bintray.com/conan/manu343726/conan-packages
  - conan remote add flexferrum https://api.bintray.com/conan/flexferrum/conan-packages
  - if [[ "${USE_BOOST_PACKAGE}" != "" ]]; then sudo apt-get install libboost-all-dev; fi

script:
  - export CXX=g++-${COMPILER_VERSION}
  - conan profile new --detect default
  - git submodule update --init
  - conan profile update settings.compiler.version=${COMPILER_VERSION} default
  - cd ${EXAMPLE_PATH}
  - ./build.sh
  - ./test.sh
