version: 1.0.0.{build}


os:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Release

environment:
  matrix:
    - BUILD_PLATFORM: x64
      EXAMPLE_PATH: conan/0.9.1
#    - BUILD_PLATFORM: x64
#      EXAMPLE_PATH: internal

matrix:
  fast_finish: false

init:
  - set BOOST_ROOT=C:\Libraries\boost_1_65_1
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%BUILD_PLATFORM%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%BUILD_PLATFORM%"=="x64" set PATH=%BOOST_ROOT%\lib64-msvc-14.1;%PATH%
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip install -q conan
  - conan user
  - conan remote add martin https://api.bintray.com/conan/martinmoene/nonstd-lite
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add manu https://api.bintray.com/conan/manu343726/conan-packages

build_script:
# - git submodule update --init
  - cd %EXAMPLE_PATH%
  - build.bat

test_script:
  - test.bat
#  - ctest -C Release -V
